name: Production CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/syncboard-backend:${{ github.sha }} -t ${{ secrets.ECR_REGISTRY }}/syncboard-backend:latest -f backend/Dockerfile.prod backend/
        docker push ${{ secrets.ECR_REGISTRY }}/syncboard-backend:${{ github.sha }}
        docker push ${{ secrets.ECR_REGISTRY }}/syncboard-backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build \
          --build-arg VITE_API_URL=${{ secrets.CORS_ORIGINS }}:8000 \
          --build-arg VITE_WS_URL=ws://100.53.237.46:8000 \
          -t ${{ secrets.ECR_REGISTRY }}/syncboard-frontend:${{ github.sha }} -t ${{ secrets.ECR_REGISTRY }}/syncboard-frontend:latest -f frontend/Dockerfile.prod frontend/
        docker push ${{ secrets.ECR_REGISTRY }}/syncboard-frontend:${{ github.sha }}
        docker push ${{ secrets.ECR_REGISTRY }}/syncboard-frontend:latest
